### ISSUE TITLE
Need Canvas Size Measurements for Paintings

### ISSUE THREAD

**Issue by Owlscape** [Provinite/halloween-2018#10]
Need canvas measurements to complete the artwork ahead of time!
Cover Page
Mobile Cover Page
Travel Cards

**Comment by Provinite** [comment]
Tarot Cards have dimensions of

`2.75" (width)` x `4.75" (height)`. To draw them at print quality, that's a 
`825 x 1425px` canvas.

**Comment by Provinite** [comment]
If we want to target `1080p` screens again, we're looking at

`1920x1080px` for desktop
`1080x1920` for mobile

**Comment by Provinite** [comment]
A likely size for the cards is going to be around `200x345px` sorry still no promises. Maybe draw around that size?
